/// Replay Timestamp data

var timeStampData = [
    {
        "gid": 9,
        "set": 2,
        "time": 18,
        "team": "DWG",
        "Likes": 1504,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 28,
        "team": "DRX",
        "Likes": 3431,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 36,
        "team": "DRX",
        "Likes": 7398,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 47,
        "team": "DWG",
        "Likes": 429,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 61,
        "team": "DRX",
        "Likes": 4332,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 92,
        "team": "DWG",
        "Likes": 2020,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 115,
        "team": "DRX",
        "Likes": 3882,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 123,
        "team": "DRX",
        "Likes": 8379,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 147,
        "team": "DRX",
        "Likes": 5331,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 170,
        "team": "DRX",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 180,
        "team": "DRX",
        "Likes": 9334,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 220,
        "team": "DRX",
        "Likes": 3319,
        "isLiked": 0,
    },
];