/// Replay Timestamp data

var timeStampData = [
    {
        "gid": 10,
        "set": 3,
        "time": 50,
        "team": "DWG",
        "Likes": 3244,
        "isLiked": 0,
    },
    {
        "gid": 10,
        "set": 3,
        "time": 100,
        "team": "GRF",
        "Likes": 1223,
        "isLiked": 0,
    },
    {
        "gid": 10,
        "set": 3,
        "time": 110,
        "team": "DWG",
        "Likes": 2214,
        "isLiked": 0,
    },
    {
        "gid": 10,
        "set": 3,
        "time": 150,
        "team": "DWG",
        "Likes": 1312,
        "isLiked": 0,
    },
    {
        "gid": 10,
        "set": 2,
        "time": 50,
        "team": "DWG",
        "Likes": 2321,
        "isLiked": 0,
    },
    {
        "gid": 10,
        "set": 2,
        "time": 100,
        "team": "GRF",
        "Likes": 3111,
        "isLiked": 0,
    },
    {
        "gid": 10,
        "set": 2,
        "time": 200,
        "team": "GRF",
        "Likes": 3351,
        "isLiked": 0,
    },
    {
        "gid": 10,
        "set": 2,
        "time": 210,
        "team": "DWG",
        "Likes": 3250,
        "isLiked": 0,
    },
    {
        "gid": 10,
        "set": 1,
        "time": 30,
        "team": "DWG",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 10,
        "set": 1,
        "time": 60,
        "team": "GRF",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 10,
        "set": 1,
        "time": 110,
        "team": "GRF",
        "Likes": 1250,
        "isLiked": 0,
    },
    {
        "gid": 10,
        "set": 1,
        "time": 130,
        "team": "DWG",
        "Likes": 2350,
        "isLiked": 0,
    },
    {
        "gid": 10,
        "set": 1,
        "time": 200,
        "team": "GRF",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 3,
        "time": 18,
        "team": "DWG",
        "Likes": 1504,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 3,
        "time": 28,
        "team": "DRX",
        "Likes": 3431,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 3,
        "time": 36,
        "team": "DRX",
        "Likes": 7398,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 3,
        "time": 47,
        "team": "DWG",
        "Likes": 429,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 3,
        "time": 61,
        "team": "DRX",
        "Likes": 4332,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 3,
        "time": 92,
        "team": "DWG",
        "Likes": 2020,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 3,
        "time": 170,
        "team": "DRX",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 3,
        "time": 180,
        "team": "DRX",
        "Likes": 9334,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 3,
        "time": 220,
        "team": "DRX",
        "Likes": 3319,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 18,
        "team": "DWG",
        "Likes": 1504,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 28,
        "team": "DRX",
        "Likes": 3431,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 36,
        "team": "DRX",
        "Likes": 7398,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 47,
        "team": "DWG",
        "Likes": 429,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 61,
        "team": "DRX",
        "Likes": 4332,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 92,
        "team": "DWG",
        "Likes": 2020,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 115,
        "team": "DRX",
        "Likes": 3882,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 123,
        "team": "DRX",
        "Likes": 8379,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 147,
        "team": "DRX",
        "Likes": 5331,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 170,
        "team": "DRX",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 180,
        "team": "DRX",
        "Likes": 9334,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 2,
        "time": 220,
        "team": "DRX",
        "Likes": 3319,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 1,
        "time": 20,
        "team": "DWG",
        "Likes": 504,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 1,
        "time": 28,
        "team": "DWG",
        "Likes": 431,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 1,
        "time": 36,
        "team": "DRX",
        "Likes": 7398,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 1,
        "time": 47,
        "team": "DWG",
        "Likes": 429,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 1,
        "time": 61,
        "team": "DRX",
        "Likes": 4332,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 1,
        "time": 92,
        "team": "DWG",
        "Likes": 2020,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 1,
        "time": 115,
        "team": "DRX",
        "Likes": 3882,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 1,
        "time": 123,
        "team": "DWG",
        "Likes": 8379,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 1,
        "time": 170,
        "team": "DRX",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 9,
        "set": 1,
        "time": 180,
        "team": "DWG",
        "Likes": 9334,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 1,
        "time": 20,
        "team": "GRF",
        "Likes": 3244,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 1,
        "time": 40,
        "team": "GRF",
        "Likes": 4222,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 1,
        "time": 70,
        "team": "APK",
        "Likes": 3421,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 1,
        "time": 100,
        "team": "APK",
        "Likes": 2546,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 1,
        "time": 150,
        "team": "APK",
        "Likes": 674,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 1,
        "time": 170,
        "team": "GRF",
        "Likes": 1632,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 1,
        "time": 200,
        "team": "APK",
        "Likes": 2543,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 2,
        "time": 25,
        "team": "GRF",
        "Likes": 4878,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 2,
        "time": 40,
        "team": "GRF",
        "Likes": 3498,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 2,
        "time": 50,
        "team": "APK",
        "Likes": 1282,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 2,
        "time": 80,
        "team": "APK",
        "Likes": 834,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 2,
        "time": 110,
        "team": "GRF",
        "Likes": 2932,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 2,
        "time": 159,
        "team": "GRF",
        "Likes": 2389,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 3,
        "time": 30,
        "team": "GRF",
        "Likes": 2643,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 3,
        "time": 50,
        "team": "APK",
        "Likes": 643,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 3,
        "time": 70,
        "team": "GRF",
        "Likes": 243,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 3,
        "time": 100,
        "team": "APK",
        "Likes": 1643,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 3,
        "time": 130,
        "team": "GRF",
        "Likes": 4231,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 3,
        "time": 150,
        "team": "APK",
        "Likes": 2590,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 3,
        "time": 160,
        "team": "GRF",
        "Likes": 2643,
        "isLiked": 0,
    },
    {
        "gid": 8,
        "set": 3,
        "time": 190,
        "team": "APK",
        "Likes": 1244,
        "isLiked": 0,
    },
    {
        "gid": 7,
        "set": 2,
        "time": 50,
        "team": "DWG",
        "Likes": 2321,
        "isLiked": 0,
    },
    {
        "gid": 7,
        "set": 2,
        "time": 100,
        "team": "T1",
        "Likes": 3111,
        "isLiked": 0,
    },
    {
        "gid": 7,
        "set": 2,
        "time": 200,
        "team": "T1",
        "Likes": 3351,
        "isLiked": 0,
    },
    {
        "gid": 7,
        "set": 2,
        "time": 210,
        "team": "DWG",
        "Likes": 3250,
        "isLiked": 0,
    },
    {
        "gid": 7,
        "set": 1,
        "time": 30,
        "team": "DWG",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 7,
        "set": 1,
        "time": 60,
        "team": "T1",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 7,
        "set": 1,
        "time": 110,
        "team": "T1",
        "Likes": 1250,
        "isLiked": 0,
    },
    {
        "gid": 7,
        "set": 1,
        "time": 130,
        "team": "DWG",
        "Likes": 2350,
        "isLiked": 0,
    },
    {
        "gid": 7,
        "set": 1,
        "time": 200,
        "team": "T1",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 2,
        "time": 18,
        "team": "GEN",
        "Likes": 1504,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 2,
        "time": 28,
        "team": "DRX",
        "Likes": 3431,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 2,
        "time": 36,
        "team": "DRX",
        "Likes": 7398,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 2,
        "time": 47,
        "team": "GEN",
        "Likes": 429,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 2,
        "time": 61,
        "team": "DRX",
        "Likes": 4332,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 2,
        "time": 92,
        "team": "GEN",
        "Likes": 2020,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 2,
        "time": 115,
        "team": "DRX",
        "Likes": 3882,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 2,
        "time": 123,
        "team": "DRX",
        "Likes": 8379,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 2,
        "time": 147,
        "team": "DRX",
        "Likes": 5331,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 2,
        "time": 170,
        "team": "DRX",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 2,
        "time": 180,
        "team": "DRX",
        "Likes": 9334,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 2,
        "time": 220,
        "team": "DRX",
        "Likes": 3319,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 1,
        "time": 20,
        "team": "GEN",
        "Likes": 504,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 1,
        "time": 28,
        "team": "GEN",
        "Likes": 431,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 1,
        "time": 36,
        "team": "DRX",
        "Likes": 7398,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 1,
        "time": 47,
        "team": "GEN",
        "Likes": 429,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 1,
        "time": 61,
        "team": "DRX",
        "Likes": 4332,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 1,
        "time": 92,
        "team": "GEN",
        "Likes": 2020,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 1,
        "time": 115,
        "team": "DRX",
        "Likes": 3882,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 1,
        "time": 123,
        "team": "GEN",
        "Likes": 8379,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 1,
        "time": 170,
        "team": "DRX",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 6,
        "set": 1,
        "time": 180,
        "team": "GEN",
        "Likes": 9334,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 1,
        "time": 20,
        "team": "HLE",
        "Likes": 3244,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 1,
        "time": 40,
        "team": "HLE",
        "Likes": 4222,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 1,
        "time": 70,
        "team": "SB",
        "Likes": 3421,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 1,
        "time": 100,
        "team": "HLE",
        "Likes": 2546,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 1,
        "time": 150,
        "team": "SB",
        "Likes": 674,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 1,
        "time": 170,
        "team": "HLE",
        "Likes": 1632,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 1,
        "time": 200,
        "team": "HLE",
        "Likes": 2543,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 2,
        "time": 25,
        "team": "HLE",
        "Likes": 4878,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 2,
        "time": 40,
        "team": "SB",
        "Likes": 3498,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 2,
        "time": 50,
        "team": "SB",
        "Likes": 1282,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 2,
        "time": 80,
        "team": "SB",
        "Likes": 834,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 2,
        "time": 110,
        "team": "HLE",
        "Likes": 2932,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 2,
        "time": 159,
        "team": "HLE",
        "Likes": 2389,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 3,
        "time": 30,
        "team": "HLE",
        "Likes": 2643,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 3,
        "time": 50,
        "team": "SB",
        "Likes": 643,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 3,
        "time": 70,
        "team": "HLE",
        "Likes": 243,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 3,
        "time": 100,
        "team": "SB",
        "Likes": 1643,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 3,
        "time": 130,
        "team": "HLE",
        "Likes": 4231,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 3,
        "time": 150,
        "team": "SB",
        "Likes": 2590,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 3,
        "time": 160,
        "team": "HLE",
        "Likes": 2643,
        "isLiked": 0,
    },
    {
        "gid": 5,
        "set": 3,
        "time": 190,
        "team": "HLE",
        "Likes": 1244,
        "isLiked": 0,
    },
    {
        "gid": 4,
        "set": 3,
        "time": 50,
        "team": "KT",
        "Likes": 3244,
        "isLiked": 0,
    },
    {
        "gid": 4,
        "set": 3,
        "time": 100,
        "team": "APK",
        "Likes": 1223,
        "isLiked": 0,
    },
    {
        "gid": 4,
        "set": 3,
        "time": 110,
        "team": "KT",
        "Likes": 2214,
        "isLiked": 0,
    },
    {
        "gid": 4,
        "set": 3,
        "time": 150,
        "team": "KT",
        "Likes": 1312,
        "isLiked": 0,
    },
    {
        "gid": 4,
        "set": 2,
        "time": 50,
        "team": "APK",
        "Likes": 2321,
        "isLiked": 0,
    },
    {
        "gid": 4,
        "set": 2,
        "time": 100,
        "team": "APK",
        "Likes": 3111,
        "isLiked": 0,
    },
    {
        "gid": 4,
        "set": 2,
        "time": 200,
        "team": "APK",
        "Likes": 3351,
        "isLiked": 0,
    },
    {
        "gid": 4,
        "set": 2,
        "time": 210,
        "team": "KT",
        "Likes": 3250,
        "isLiked": 0,
    },
    {
        "gid": 4,
        "set": 1,
        "time": 30,
        "team": "KT",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 4,
        "set": 1,
        "time": 60,
        "team": "APK",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 4,
        "set": 1,
        "time": 110,
        "team": "APK",
        "Likes": 1250,
        "isLiked": 0,
    },
    {
        "gid": 4,
        "set": 1,
        "time": 130,
        "team": "KT",
        "Likes": 2350,
        "isLiked": 0,
    },
    {
        "gid": 4,
        "set": 1,
        "time": 200,
        "team": "APK",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 2,
        "time": 18,
        "team": "DWG",
        "Likes": 1504,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 2,
        "time": 28,
        "team": "AF",
        "Likes": 3431,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 2,
        "time": 36,
        "team": "AF",
        "Likes": 7398,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 2,
        "time": 47,
        "team": "AF",
        "Likes": 429,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 2,
        "time": 61,
        "team": "AF",
        "Likes": 4332,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 2,
        "time": 92,
        "team": "AF",
        "Likes": 2020,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 2,
        "time": 115,
        "team": "AF",
        "Likes": 3882,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 2,
        "time": 123,
        "team": "AF",
        "Likes": 8379,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 2,
        "time": 147,
        "team": "AF",
        "Likes": 5331,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 2,
        "time": 170,
        "team": "AF",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 2,
        "time": 180,
        "team": "AF",
        "Likes": 9334,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 2,
        "time": 220,
        "team": "AF",
        "Likes": 3319,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 1,
        "time": 20,
        "team": "AF",
        "Likes": 504,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 1,
        "time": 28,
        "team": "DWG",
        "Likes": 431,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 1,
        "time": 36,
        "team": "AF",
        "Likes": 7398,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 1,
        "time": 47,
        "team": "DWG",
        "Likes": 429,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 1,
        "time": 61,
        "team": "AF",
        "Likes": 4332,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 1,
        "time": 92,
        "team": "DWG",
        "Likes": 2020,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 1,
        "time": 115,
        "team": "AF",
        "Likes": 3882,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 1,
        "time": 123,
        "team": "DWG",
        "Likes": 8379,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 1,
        "time": 170,
        "team": "AF",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 3,
        "set": 1,
        "time": 180,
        "team": "DWG",
        "Likes": 9334,
        "isLiked": 0,
    },{
        "gid": 2,
        "set": 1,
        "time": 20,
        "team": "HLE",
        "Likes": 3244,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 1,
        "time": 40,
        "team": "HLE",
        "Likes": 4222,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 1,
        "time": 70,
        "team": "GRF",
        "Likes": 3421,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 1,
        "time": 100,
        "team": "HLE",
        "Likes": 2546,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 1,
        "time": 150,
        "team": "GRF",
        "Likes": 674,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 1,
        "time": 170,
        "team": "GRF",
        "Likes": 1632,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 1,
        "time": 200,
        "team": "HLE",
        "Likes": 2543,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 2,
        "time": 25,
        "team": "HLE",
        "Likes": 4878,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 2,
        "time": 40,
        "team": "GRF",
        "Likes": 3498,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 2,
        "time": 50,
        "team": "GRF",
        "Likes": 1282,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 2,
        "time": 80,
        "team": "GRF",
        "Likes": 834,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 2,
        "time": 110,
        "team": "HLE",
        "Likes": 2932,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 2,
        "time": 159,
        "team": "GRF",
        "Likes": 2389,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 3,
        "time": 30,
        "team": "HLE",
        "Likes": 2643,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 3,
        "time": 50,
        "team": "GRF",
        "Likes": 643,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 3,
        "time": 70,
        "team": "HLE",
        "Likes": 243,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 3,
        "time": 100,
        "team": "GRF",
        "Likes": 1643,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 3,
        "time": 130,
        "team": "HLE",
        "Likes": 4231,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 3,
        "time": 150,
        "team": "GRF",
        "Likes": 2590,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 3,
        "time": 160,
        "team": "HLE",
        "Likes": 2643,
        "isLiked": 0,
    },
    {
        "gid": 2,
        "set": 3,
        "time": 190,
        "team": "HLE",
        "Likes": 1244,
        "isLiked": 0,
    },
    {
        "gid": 1,
        "set": 2,
        "time": 50,
        "team": "GEN",
        "Likes": 2321,
        "isLiked": 0,
    },
    {
        "gid": 1,
        "set": 2,
        "time": 100,
        "team": "SB",
        "Likes": 3111,
        "isLiked": 0,
    },
    {
        "gid": 1,
        "set": 2,
        "time": 200,
        "team": "GEN",
        "Likes": 3351,
        "isLiked": 0,
    },
    {
        "gid": 1,
        "set": 2,
        "time": 210,
        "team": "SB",
        "Likes": 3250,
        "isLiked": 0,
    },
    {
        "gid": 1,
        "set": 1,
        "time": 30,
        "team": "SB",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 1,
        "set": 1,
        "time": 60,
        "team": "GEN",
        "Likes": 4250,
        "isLiked": 0,
    },
    {
        "gid": 1,
        "set": 1,
        "time": 110,
        "team": "GEN",
        "Likes": 1250,
        "isLiked": 0,
    },
    {
        "gid": 1,
        "set": 1,
        "time": 130,
        "team": "SB",
        "Likes": 2350,
        "isLiked": 0,
    },
    {
        "gid": 1,
        "set": 1,
        "time": 200,
        "team": "SB",
        "Likes": 4250,
        "isLiked": 0,
    },
];